esp32:
  board: esp32dev

esphome:
  name: espairqualoutput


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "espairqualFallback"
    password: "espairqual"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


uart:
  rx_pin: GPIO21
  tx_pin: GPIO23
  baud_rate: 9600

sensor:
  - platform: pmsx003
    type: PMS5003T

    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
    pm_10_0:
      name: "Particulate Matter <10µm Concentration"
    pm_1_0:
      name: "Particulate Matter <1µm Concentration"
    temperature:
      name: "PMS Temperature"
    humidity:
      name: "PMS Humidity"
    update_interval: 120s
