name: "Fabrication"
on:
  push:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '**kibot.yaml'
  pull_request:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '**kibot.yaml'
    tags:
      - pcb-v*
  workflow_dispatch:
  workflow_call:

jobs:
  fabrication:
    name: fabrication
    uses: gcormier/kicad-jobs/.github/workflows/kicad-fabrication.yaml@main
  
  push_render:
    runs-on: ubuntu-latest
    name: render
    needs: fabrication
    steps:
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automatic update"
          file_pattern: '*.png'
          repository: ./images